# Generated by Django 4.2.5 on 2023-10-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bandfrequency", old_name="user", new_name="user_band",
        ),
    ]
