# Generated by Django 4.2.5 on 2023-10-07 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandfrequency",
            name="users",
            field=models.ManyToManyField(
                related_name="band_frequencies", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
