# Generated by Django 4.2.5 on 2023-10-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_bandfrequency_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bandfrequency", old_name="users", new_name="band_frequency",
        ),
    ]
